#+title: 2022 Year End Book Review
#+date: <TODO>
#+filetags: reading review

* /The Complete Short Stories of Fyodor Dostoevsky/ (★★★★★ 5/5)

It's difficult to rate a collection of short stories. Even more so, it's difficult to find a collection where each story is as enriching as the next. Well, it's easy for me to give this collection a five, even in toto. Moreover, I assert, no story was any less enjoyable than the next.

Of course, I'm a little biased -- Dostoevsky is my favorite author. Though this is the case, at times I've struggled to finish his longer works. The short stories were wonderful because they were each gripping and, well, short!

| *How I found it*              | I sought it out                                                        |
| *Recommend for*               | Readers of classics, short stories, Russian literature, Dosteovsky     |
| *"Buy test"*                  | I would buy this for a friend who falls into the *recommended for* set |
| *Approx. time I took to read* | A month                                                                |
| *One sentence summary*        | Mishaps in Russia and the psychology of an 19th Century Russian        |
| *Standalone*                  | Yes                                                                    |
  
* /I'm Thinking of Ending Things/ (★★★⯪☆ 3.5/5)

I had never heard of this book before but I read it for a book club. It struck me as being a postmodern, psychological thriller type of novel. This isn't in my normal line of reading so I reserve the right to be wholly off with that categorization.

I did enjoy it and found myself in suspense at times. It evokes a /spooky/ feeling and contains a few twists and turns. I will mention, however, (at the risk of a spoiler -- skip this paragraph if you don't wanna hear it) I did find the ending to be quite predictable.

As book club books go, it was a pretty good one and spurred some interesting discussions. Around that topic I would so a few things, if you're looking to discuss or watch the movie:
 - the book club questions in the back of the novel are no where near as interesting as they could be.
 - don't expect the movie to be /anything/ like the book. Aside from bearing the same title and having a few events in common, they are practically unrelated.

| *How I found it*              | Picked by other member of book club                              |
| *Recommend for*               | Readers of psychological thrillers, folks who like "weird" books |
| *"Buy test"*                  | I probably wouldn't buy it for anyone                            |
| *Approx. time I took to read* | A week                                                           |
| *One sentence summary*        | Young lovers float along a river of oddity                       |
| *Standalone*                  | Yes                                                              |
  
* /Our Thoughts Determine Our Lives/ (★★★★⯪ 4.5/5)
  
This was a very nice book along the vein of other Orthodox spirituality books I've read in recent years. Elder Thaddeus lived a most interesting life, filled with many spiritual lessons. This book is an expounding thereabouts.
  
| *How I found it*              | Saw it in our church's bookstore                                          |
| *Recommend for*               | Orthodox Christians or those interested in spiritual life                 |
| *"Buy test"*                  | I would buy this for friends who fall into the  *recommended for* section |
| *Approx. time I took to read* | Three weeks                                                               |
| *One sentence summary*        | Our thoughts determine our lives                                          |
| *Standalone*                  | Yes                                                                       |

* /The Rust Programming Language/ 
  
* /The Republic of Thieves/ 
  
* /Endurance/ 
  
* /Pushkin Poems/ 
  
* /How Design Makes the World/ 
  
* /On the Cosmic Mystery of Jesus Christ/ 
  
* /Moby Dick/
  
* /On the Divine Images/ 
  
* /Early Christian Doctrines/ 
  
* /The Name of the Wind/ 
  
* /Notes from the Underground/ 
  
* /War and Peace/
  
* /The Name of the Wind/ (★★⯪☆☆ 2.5/5)

Things I didn't like
 - Felt like a collection of side-quests
 - No major resolution for such a long (intro) book
 - Characters felt 1-dimensional (couldn't distinguish his friends, women all seemed like the same character)
 - Lots of repetition: gotta make tuition trope, main character always "realizes female character X is beautiful"
 - Auri (sewer girl) gave off an odd anime, crazy and cutesy vibe and I found myself cringing while reading this character
 - It felt like a Harry Potter wannabe at times
 - Plot was mostly bust with formulaic booms (character takes massive risk then gets a major reward or setback)
 - Some dialog and writing pulled us out of the "fantasy world" into clear early 2010s zeitgeist (e.g. debating modern idioms, character's sensibilities, citing formal logical fallacies)
 - Main character was something of an übermensch
 - Felt like author was projecting his ideals onto the main character
 - Spoilers on the back of the book, kind of, I guess

I think I would have enjoyed this more if I had
 - Entered it expecting young adult fantasy
 - Known it wouldn't resolve anything (and that the second book was so long and third forthcoming)
 - Not read /The Lies of Locke Lamora/ so recently which had similarities but set too high a bar

The book was fan-service to reading. The main character's dream place was the Archives, he was seeking stories and look at the setting. A scribe was transcribing Kovthe telling his story, which at times even included embedded story tellers.

| *How I found it*              | Picked by other member of book club                               |
| *Recommend for*               | Fans of young adult fantasy                                       |
| *"Buy test"*                  | I would only buy this for a friend who specifically asked for it  |
| *Approx. time I took to read* | A week and a half                                                 |
| *One sentence summary*        | The childhood backstory of an incredibly gifted mage and musician |
| *Standalone*                  | No                                                                |
