#+title: Overly Ambitious October Challenges
#+date: <TODO>
#+filetags: reading books skateboarding writing orthodox

I have long been a fan of 30 day challenges. 30 days is the perfect amount of time to try something new or stretch yourself. This October I have the invaluable blessing of having a little more time on my hands. So I'm going to try out a bunch of October challenges and see how I fare.

I have in mind 26 challenges some of which are well known, some are novel. I don't expect to deliver on 100% of these challenges, however, I will give myself partial credit where applicable. I also have a loose priority in my mind which won't be reflected herein.

So, here are the challenges!

* Challenges
** Inktober (AKA Drawtober) 
   
This is a well-known October challenge. The goal is to draw something, absolutely anything, each day. The drawing can be simple or complicated to any degree.

This challenge is meant to be a streak so missed days cannot be made up.

** Skateober

The idea of this challenge is to do a different trick for every day of the month (so 31 tricks).

Since the weather is temperamental where I live, I'm going to allow these tricks to cluster however they may. For example, I would consider this a success if I did all the tricks in two sessions.

** Booktober

Read 4 books in the October.

This shouldn't be difficult for me since I've been reading at a quicker pace than 4 books this year. I will also count books that I end up reading aloud and I'll take partial credit for books that I _finish_ in October (e.g. I'll count the second half of a book as half a book).
  
** Photober

This is similar to Inktober except for photography. It's meant to be a streak so skipped days can't be made up. Photos must vary but not extremely so.

** Psalmtober

Pray the entire Psalter in October. This could be clustered if need be but daily prayer is preferred.

** Sober October

No alcohol consumption in the month of October.

** Hasktober

Have some interaction with the Haskell programming language 31 times in October.

This may include
 - writing a little code
 - modifying an existing program
 - trying a new library
 - reading a Haskell paper
 - writing about Haskell
 - publishing a video about Haskell

** Writober

Write something every day.

I'm going to keep this kind of fuzzy but I'll know if I've met it or not. This is another "streak-based" goal (e.g. skipped days are losses).

** YouTober

Publish a video for each day in October.

Hopefully I can leverage other challenges for this one (e.g. Skateober).

I use the word "publish" because I will allow for publishing videos that I've already recorded (I have a few).

** Langtober

Practice DuoLingo every day.

This shouldn't be too difficult. Again this will be streak-based and "streak freezes" (a DuoLingo feature that allows you to skip a day) won't count.

** Musictober

Practice a musical instrument for 30 minutes a day. This will probably be non-streak-based so, for example, an hour may count for two days.

** Curiousitober

Come up with and answer 1 interesting question per day. This is streak-based.

** Exertober

Exercise 6 days a week for the month. This will allow for 4 "skip" days for resting.

** Unplugtober

No internet-connected devices, except where necessary for other challenges.

Some exceptions that come to mind
 - Hasktober will require the internet often (e.g. to read docs)
 - YouTober will require the internet to publish videos
 - Curiositober will likely require the internet to find answers

This is streak-based.   

** Walktober

Go on a walk (or run), outside every day. I'd prefer this to be daily but will allow for some "double day walks" to count for two.
  
** Voictober
    
Read aloud one book.

If finished, I will count this as a point towards Booktober too.

** Cooktober
    
Cook anything each day. Can be repeats.

This is to help me learn how to cook and practice cooking. Since this will be tough for me I would definitely count multiple recipes in a single day as multiple days. 

** Thriftober

Unless necessary spending or challenge-related, spend less than $31 in October.

If I went over $31 I'll need to figure out a partial credit mechanism, however, I hope I won't need to do that.

** Churchtober
   
Go to every church service in October. 

This will be quite a challenge as there are many services.

** Whittletober
    
Whittle every day.

** Optober
   
Focus on optimism. No negativity, if you slip you've gotta say 3 nice things.

** Brotober
    
Hang with your brother all month.

My brother will be staying with me for the month and hopefully participating in some of these challenges!

** Gametober
    
Play 31 distinct, non-video games in October. Multiples are allowed in a single day and skips are acceptable.

** Drive Test Tober 
    
Help my brother pass the state driving test.

** Dishtober 

Be the only one in the house that does dishes. I'd get a free pass on this one if someone did them while I was away.

** Thinktober
    
Spend a half-an-hour a day thinking.

This one's a bit random but should be interesting.

* Conclusion

Well there are the overly ambitious October goals. I'm gonna give them my best shot and I'll try to post updates regularly.
