#+title: How I Learned Rock To Fakie
#+date: <2022-05-25 01:23>
#+filetags: skateboarding trick_tip howto

/4 minute read/ | [[https://www.youtube.com/watch?v=ICj6qQPXnkQ][Video Version]] 

I found Rock To Fakie to be an elusive trick. Looking back through my skating log, it took 3 months (to the day) for me to land my first one. If my books are correct, I practiced this trick for 53 sessions before landing! Though I usually wouldn't /only/ practice Rock To Fakie in a session, that's still a lot of sessions!

So, how did I manage to finally land one? Let's get into it.

For starters, I watched every trick tip video I could find. The videos that stood out were:
 - [[https://www.youtube.com/watch?v=vabaAivHplc][Ben Degros' video]]
 - [[https://www.youtube.com/watch?v=KTtRbd8FwfM][The Skate Park Lessons' video]]
 - [[https://www.youtube.com/watch?v=04FwNWlM6ZM][Sketchy Dave's video]]
 - [[https://www.youtube.com/watch?v=pUtYR-K1UP0][Never Stop Improving's video]]
 - [[https://www.youtube.com/watch?v=bElNF5oL1XQ][Trog Army's video]]

I dissected these videos among others. I scoured various web forums and even got a few tips from friends. All this was to no avail. Let's walk through some of the tips I encountered and why they didn't work for me.

* Taps and Lifts

In trick tip videos, skaters recommend doing little taps. Doing these higher and higher up the ramp while going fakie should lead to Fakie Tail Stall makes. This actually worked out great for me. I got a few little Tail Taps on the coping after a few sessions which evolved into full stalls in short order.

Supposedly, doing little tail taps (or lifts) right before going fakie teach you how to lift the board. This lift is the last part of a Rock To Fakie. This didn't work out for me.

The forward lifts got comfortable for me. They lead to consistent Uptowns (an underrated trick) and Manual To Fakies. Though comfortable, These lifts didn't seem to help my Rock To Fakies. Whenever I'd try an actual Rock to Fakie something in my weight distribution was way off. I couldn't seem to correct it.

* Eyes and Shoulders

Some videos claim that the key elements to this trick are:
 - keeping your shoulders perpendicular to the ramp and
 - keeping your eyes looking where you want to go.

Keeping your shoulders straight is important but there's some give here. It's clear to me now that shoulder placement wasn't blocking me from learning the trick. Regarding eyes, when I thought about where I was looking I tended to over-think it. This made for some silly (and painful) attempts.

* Confidence 80/20

Many resources claim that, in actuality, your form only makes up 20% of your ability to execute the trick. The other 80%? Confidence. This may be true for some but it wasn't for me. The "just be confident" advice tends to feel like "just do the thing" advice. Though well-meaning, it is superficially useful. I had a mental block. Hoping for a burst of confidence wasn't cutting through it.

* Other Little Tricks

I tried many other tricks (in many a combination) including:
 - being loud -- both shouting and loudly slamming the rock
 - doing the trick on the exhale -- exhales being calming actions
 - leaning farther back
 - steeper ramps
 - more mellow ramps
 - smaller ramps
 - long sessions and short sessions
 - trying the trick alone and in combos
 - closing my eyes
 - wearing more pads -- to try to gain confidence
 - likely a few other tactics that escape me now

Through all this my right hip screamed for vengeance -- it took a ton of slams!

* What Worked For Me

In the midst of battling Rock To Fakies, I learned Rock And Rolls (R&Rs). I got the breakthrough for R&Rs from a Never Stop Improving [[https://www.youtube.com/watch?v=WIsJM8v01uI][video]]. In that video, Justin demonstrates "stabbing" the board forward (a little tap) then kick turning back into the ramp. Doing this gradually up the ramps, you eventually hit the coping. A little later you find you're doing it above the coping and viola! You can Rock And Roll. These little baby R&Rs slowly become real rocks then legendary decked R&Rs as you push your abilities, a bit at a time. This was the same incremental approach that worked for me for finally making Rock To Fakies.

The steps in my thought process were: ride up, stab the ramp (do a tap), the pull the board up (as in do a "lift") and ride away. Thinking of the motion as an actual "stabbing" of the board was key, it changed my entire perspective on the trick. I did this stab higher and higher until I started to stab the coping. Then, putting a slight bit more speed behind it, I found I was doing the stab above the coping. A small but sure Rock To Fakie! These Rock To Fakies grew with practice in the exact same way that R&Rs did. Now I can deck them out, land them on bigger ramps and do some odd variants.

* Don't Discount The Other Tips

I stand by the assertion that the Never Stop Improving video provided the breakthrough for me. Though this is true, I can't discount the other tips mentioned herein. It's hard to say what they contributed to my progress while learning Rock To Fakies -- They all played a part in the journey. Also, we all know that everyone learns differently. The Never Stop Improving video got /me/ over the hurdle -- but I'm curious -- what was your journey to Rock To Fakies like?
