#+title: October Challenges Update 1
#+date: <2022-10-10 10:47>
#+filetags: reading books skateboarding writing orthodox art music exercise gaming

Now that it's the 10th, I figured it'd be a good time to post an update on my October challenges! So far they're going well, though it has been difficult to maintain.

See the [[https://mjgpy3.github.io/me/overly-ambitious-october-challenges.html][original post]] for more details on exactly what each challenge entails and each challenge's rubric for success.

Let's step through were we're at with each challenge.

* Challenges
** Inktober (AKA Drawtober)
   
I'm pretty happy with my results so far for this challenge. I'm especially happy as one who isn't all that "artistic". I've mostly drawn items from around my house or tried to draw the art of others (for practice, of course). A the end of the month I'll post all may drawings but so far I've managed to do a doodle every day!

Here are some teasers of my doodles from the last 9 days:

 - "Bug-car" from kids' toy
 - Schema cross
 - Spooky Pooky
 - Big Daddy
 - Penguin & Lil' Pookie
 - Hobbes stuffie
 - Endurance
 - Crest
 - Lukhimov Ent

** Skateober

This challenge has also been a success so far. I certainly haven't been skating as much as usual but I've managed to do "a trick per day". I _have_ clustered these into a few sessions but that's perfectly acceptable from the challenge description.

Here's a playlist of the tricks completed so far: https://www.youtube.com/playlist?list=PL97kkzI__pGzvRuON8V_JSRg2VgGON7jc
   
** Booktober

This has been going well and I'm ahead of schedule. I read /Making Comics/ and my brother and I finished /As A Man Thinketh/. I haven't been reading as much this month, unfortunately, but the other challenges have been fun.
   
** Photober

So far this has been a success. Here are teasers of what I've snapped so far:

 - Wilted rose
 - Dew on holly
 - Record spinning
 - Bug on the ramp
 - Duck with fish
 - Hobbes stuffie
 - Orange tree
 - Goat
 - Red green bush
 - Piano keys

** Psalmtober

This is perfectly on target. We've been praying the Psalms each morning.
   
** Sober October

Success so far -- no alcohol since last month!
   
** Hasktober

So far so good. I've mostly been reading articles. I'll share which ones at a later date.
   
** Writober

This has been going well. I've mostly written private journal entries, however, I also wrote a note to my wife, the original challenge post, a few book reviews (for the year end book review), and this post!
   
** YouTober
   
So far so good. I've already shared the skate trick playlist above but I've also posted 3 or 4 other skateboarding videos that I've been meaning to publish.

** Langtober

So far so good, DuoLingo every day.
   
** Musictober
   
I've practiced (mainly mandolin) 359 minutes so far. Out of a goal of 930 minutes, I'd say this is ahead of schedule.

** Curiousitober
   
This has been good. My only problem has been that I've often delayed the question until the end of the day.

So far my questions have been:

 - Is there a deeper meaning of /Blood Meridian/?
 - How did chess come about and develop?        
 - Why do we say "turn over a new leaf"?       
 - Who is "Katari" in Brendan's Death Song?   
 - What is the difference between a crocodile and an alligator?
 - Where does ALDI USA's food come from?                      
 - Why do some classics have names/places blanked out?       
 - What is second person and does anything use it?          
 - How did people greet each other before "hello"?         
 - When is the best time to eat protein (relative to exercise)? 

I may later elaborate on each question and post some of the answers I've found.   
 
** Exertober
   
I'm actually ahead of schedule with this one. Since I skated for a while on Sunday I've counted it as a workout which means I've got a few extra skips saved up.

** Unplugtober

This is going well so far. Aside from a quick daily checkup of email and whatnot I've only been using the internet for very specific purposes. I'm wasting very little time browsing the web which feels great. I may try to make a standard around this challenge -- we'll see.
   
** Walktober

So far so good. I've been counting some very long walks (e.g. we went to the zoo for a few hours) as two walks. This may be cheating but it's hard to get out on a walk in a cold, rainy day.
  
** Voictober

We're about half way through /iRobot/ so this challenge is ahead of schedule.
   
** Cooktober

I've been cooking large breakfasts almost every day for my family. Due to that and a few extra grill outs and cooking sessions, I'm slightly ahead on this challenge.
   
** Thriftober

This is going well. I've only spent $5 on a few books.
   
** Churchtober

I had to miss one service due to a family party but this is going fine otherwise.
   
** Whittletober

I've managed to rough out a chess pawn each day. So I'd call this a success so far.
   
** Optober

This challenge is really difficult to quantify. It's kind of fuzzy and I'm sure I've missed opportunities or been pessimistic on auto-pilot. I think I'm going to do a longer more thought up write up on this at the end of the month. One thing I will say is that the challenge has made me a little more introspective which is, of course, a good outcome.
   
** Brotober
   
I've hung out with my brother (and others in fact) every day so far!

** Gametober

I'm a little ahead on this one as well. So far I've played:

 - Chess
 - Foosball
 - Pentago
 - Rummikub
 - 40K mission 1
 - Zombie Dice
 - Go fish
 - Jenga
 - Solitaire
 - Pandemic: The Cure
 - Carcassone
   
** Drive Test Tober 

This has been going okay. I've been encouraging my brother to study the driver's manual. I've also been trying to help him with practice tests. We'll see how it works out.

** Navy Shower Tober

This has been brutal. It's been colder in our house and our water has been colder so this has been quite difficult. I've still managed to avoid hot showers so far but we'll see for how long.
   
** Dishtober 

A family member did them once while I was away but other than that I've done them multiple times every day.

** Caff-free Tober
   
I haven't had any caffeine, intentionally. I guess it's hard to avoid if it's in chocolate and whatnot. But I haven't had any coffee or anything drinks that I know contain caffeine.

** Rectober

This is well ahead of schedule. I've listened to 20 albums already!
   
* Conclusion

So far everything is going well. As I mentioned, it's difficult to fit everything into a single day. I'm no planning on backing down from these challenges.
